services:
  - type: web
    name: stockproject-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://<username>:<password>@cluster.mongodb.net/smartstock
      - key: SECRET_KEY
        generateValue: true
