services:
  - type: web
    name: stockproject-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MONGO_URI
        value: mongodb+srv://admin:admin%40123@cluster0.7gdyfy9.mongodb.net/?appName=Cluster0
      - key: SECRET_KEY
        generateValue: true
